
  # list all the global configurations of this api in this file 

http:
  host: "0.0.0.0"
  port: "8082"
  basePath: "/api/*"

salesforce:
  username: "madhavag440@gmail.com"
  authUrl: "https://login.salesforce.com/services/Soap/u/60.0"

untilSuccessful:
  maxRetries: "2"
  frequency: "30000"

mule:
  appId: "20097336"